### ISSUE TITLE
Add MINQ

### ISSUE THREAD

**Issue by wildsm** [POptUS/IBCDFO#31]
Once Minq is public, a submodule should be created in the top level of IBCDFO and the IBCDFO README (and possibly READMEs of solvers that employ MINQ) to note the issues with submodules.

Furthermore, MINQ should have an updated release/develop/contrib process to reflect that changes should be propagated to submodules such as the one in IBCDFO.

**Comment by jmlarson1** [comment]
> Need to update README to note that people will need to `git submodule update --init --recursive` to get the content in the submodules, then can close this issue.

Addressed by #54
