### ISSUE TITLE
Missing files in python pounders tests

### ISSUE THREAD

**Issue by jmlarson1** [POptUS/IBCDFO#63]
All python unit tests

https://github.com/POptUS/IBCDFO/tree/main/pounders/py/tests/unit_tests

and a python regression test

https://github.com/POptUS/IBCDFO/blob/main/pounders/py/tests/regression_tests/callpounders.py

depend on the existence of some `.mat` files that aren't in the repo. 

Either the scripts for producing the necessary inputs should be in included, or these tests should be removed. It is not clear what specific issues they are trying to test, so it might be proper to remove some (but not all) test files.

**Comment by jared321** [comment]
Such files can be included in the python package if needed.  I have done this in the path with other packages.

**Comment by jmlarson1** [comment]
These test were moved to the `old_unit_tests` directory in commit 8d56084fa4ec42db5e471329f6600e2f6138b24d. This is sufficient for now.
